// <auto-generated />
using AleMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AleMvc.Migrations
{
    [DbContext(typeof(MioDbContext))]
    partial class MioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AleMvc.Models.Lezioni", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Docente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Docente")
                        .HasColumnType("int");

                    b.Property<int>("Id_lezione")
                        .HasColumnType("int");

                    b.Property<string>("TitoloLezione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Id_Docente");

                    b.ToTable("Lezioni");
                });

            modelBuilder.Entity("AleMvc.Models.Nuoviutenti", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("AleMvc.Models.Lezioni", b =>
                {
                    b.HasOne("AleMvc.Models.Nuoviutenti", "utente")
                        .WithMany("Lezione")
                        .HasForeignKey("Id_Docente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utente");
                });

            modelBuilder.Entity("AleMvc.Models.Nuoviutenti", b =>
                {
                    b.Navigation("Lezione");
                });
#pragma warning restore 612, 618
        }
    }
}
